### ISSUE TITLE
Crash in Kvantum::WindowManager::canDrag

### ISSUE THREAD

**Issue by muesli** [tsujan/Kvantum#173]
Clicking the settings button (or pretty much any other toolbar button) in KDE Telepathy's contact-list causes a crash with Kvantum.

Kvantum 0.10.5 with Qt 5.10.0

```
#0  0x00007fffda2e2c22 in Kvantum::WindowManager::canDrag(QWidget*, QWidget*, QPoint const&) ()
    at /usr/lib/qt/plugins/styles/libkvantum.so
#1  0x00007fffda2e72dc in Kvantum::WindowManager::mousePressEvent(QObject*, QEvent*) () at /usr/lib/qt/plugins/styles/libkvantum.so
#2  0x00007ffff32b5eac in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff5523e18 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff552bd91 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff32b61e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff552ad1a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
```

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/Kvantum/commit/4f5ccd72b2576d9478846ddda79a4c74150d7128. Please update to the latest git source!

Thank you very much for reporting! I'll make a new release soon -- I hate crashing bugs.
